version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: weekly
      day: friday
      time: "00:00"
      timezone: Europe/Berlin
    labels:
      - "\U0001F4E6 dependencies"
      - "\U0001F916 bot"
