version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  labels:
  - "\U0001F4E6 dependencies"
  - "\U0001F916 bot"
  ignore:
  - dependency-name: "@date-io/luxon"
    versions:
    - "> 1.3.13"
