version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - tms_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  tms-server:
    image: tutor-management-system
    container_name: tms-server
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - tms_db
    volumes: 
      - ./server/config/default.yml:/tms/server/config/default.yml

volumes:
  db-data:

networks:
  tms_db:
