version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - tms_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_data:/data/db

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    networks:
      - tms_db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  tms-server:
    image: tutor-management-system
    container_name: tms-server
    restart: on-failure:1
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    networks:
      - tms_db
    volumes:
      - ./server/config:/tms/server/config

volumes:
  db_data:

networks:
  tms_db:
