version: "3.1"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - tms_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    networks:
      - tms_db
    ports:
      - 8081:8081
    environment:
      # Make sure they match the ones above
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  tms_db:
