version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - tms_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      # Replace with the path to the folder in which the db-files should be persisted.
      - <path-to-DB-FOLDER>:/data/db

  tms-server:
    # Adjust the image with the version you want to use. If you do not use 'latest' updating the container will be easier in the future.
    image: ghcr.io/dudrie/tutor-management-system:<version>
    container_name: tms-server
    restart: on-failure:1
    cap_add:
      # This one is needed so puppeteer properly works inside the container (see: https://developers.google.com/web/tools/puppeteer/troubleshooting#tips)
      - SYS_ADMIN
    depends_on:
      - mongo
    networks:
      - proxy_network
      - tms_db
    environment:
      TMS_MONGODB_USER: ${MONGO_USER}
      TMS_MONGODB_PW: ${MONGO_PASSWORD}
      TMS_SECRET: ${TMS_SECRET}
    volumes:
      # Replace with the path to the folder containing the configuration and template files of the TMS.
      - <path-to-CONFIG>:/tms/server/config

volumes:
  db_data:

networks:
  tms_db:
  proxy_network:
