database:
  databaseURL: 'mongodb://localhost:27017/tms'
  secret: 'keyboard cat'
  config:
    useNewUrlParser: true
    # This is needed bc of the docker-compose file
    authSource: 'admin'
    auth:
      user: 'root'
      password: 'example'
    authMechanism: 'SCRAM-SHA-1'

mailing:
  service: 'gmail'
  auth:
    type: 'OAuth2'
    user: 'USER-MAIL'
    clientId: 'clientId'
    clientSecret: 'clientSecret'
    refreshToken: 'refreshToken'
