# Session timeout after inactivity in minutes.
sessionTimeout: 120

# (Optional) If the app is hosted on a prefixed path (ie https://example.com/foo) set this property to the prefix (ie "foo"). If the app is hosted on the root path this property can be omitted.
# prefix: derpy

database:
  databaseURL: 'mongodb://localhost:27017/tms-nestjs'
  maxRetries: 2
  config:
    # This is needed bc of the docker-compose file
    authSource: 'admin'
    authMechanism: 'SCRAM-SHA-1'

mailing:
  testingMode: true
  host: HOST
  port: 587
  auth:
    user: USER
    pass: PASS
