# Session timeout after inactivity in minutes.
sessionTimeout: 120

# (Optional) If the app is hosted on a prefixed path (ie https://example.com/foo) set this property to the prefix (ie "foo"). If the app is hosted on the root path this property can be omitted.
# prefix: derpy

database:
  databaseURL: 'mongodb://localhost:27017/tms-nestjs'
  maxRetries: 2
  config:
    # This is needed bc of the docker-compose file
    authSource: 'admin'
    authMechanism: 'SCRAM-SHA-1'

mailing:
  testingMode: false
  host: 'SERVER'
  port: 587
  from: 'MAIL'
  auth:
    user: USER
    pass: PASS
  # Replacements:
  # {{name}}: Name of user
  # {{username}}: Username of user
  # {{password}}: Temporary password of user
  template: "Hallo {{name}},\n
    \n
    hier sind deine Zugangsdaten zum Tutor-Management-System:\n
    \n
    Nutzername: {{username}}\n
    Passwort: {{password}}\n
    \n
    Mit freundlichen Grüßen\n
    TMS Admin"
