name: Auto Merge Dependabot PRs
on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # Use a special token which has push permissions.
          github-token: ${{ secrets.GH_AUTO_MERGE_TOKEN }}
          # Do not automatically approve the PR because it looks like an actual human has reviewed it. 
          # This does not interfere with the auto merging.
          approve: false
          target: minor
