name: Build and push Docker image

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  build_and_push:
    name: Build and push the docker image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository
        uses: actions/checkout@v2
      
      # Setting up Buildx because it's needed by build-push-action
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      
      # Login to repository
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      
      - name: Build and push the image
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: ghcr.io/dudrie/tutor-management-system:${{ github.event.release.tag_name }}
