name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  type-check-client:
    name: Type Check Client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node packages
        run: |
          yarn install
        env:
          CI: true
      - name: Type check client
        working-directory: client/
        run: yarn ts:check
        env:
          CI: true

  type-check-server:
    name: Type Check Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node packages
        run: |
          yarn install
        env:
          CI: true
      - name: Type check server
        working-directory: server/
        run: yarn ts:check
        env:
          CI: true

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node packages
        run: |
          yarn install
        env:
          CI: true
      - name: Check code quality in workspace
        run: |
          yarn workspaces run prettier:check
          yarn workspaces run eslint:check
        env:
          CI: true
