name: Create Docker image

on:
  release:
    types: [created] 
    branches:
      - master

jobs:
 build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Create image
        run: yarn docker:build
        env:
          CI: true
      - uses: actions/upload-artifact@master
        with:
          name: tutor-management-system
          path: ./Tutor-Management-System.tar
 
