name: Build and Deploy Docs

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - add-documentation

jobs:
  # check-build:
  #   if: github.event_name != 'push' # We have a pull_request event.
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
  #       with:
  #         persist-credentials: false

  #     - name: Setup Node.js 🧱
  #       uses: actions/setup-node@v2.1.2
  #       with:
  #         node-version: 12.x

  #     - name: Install node packages 📦
  #       run: |
  #         yarn install --frozen-lockfile
  #       env:
  #         CI: true

  #     - name: Build docs 🔧
  #       working-directory: docs/
  #       run: |
  #         yarn build

  build-and-deploy:
    # if: github.event_name != 'pull_request' # We have a 'push' event.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js 🧱
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install node packages 📦
        run: |
          yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build docs 🔧
        working-directory: docs/
        run: |
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
