name: Docker image test
on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main

jobs:
  test-docker-image:
    name: Test Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install node packages
        run: |
          yarn install
        env:
          CI: true
      - name: Test docker image
        working-directory: scripts/
        run: yarn run ts-node ./build-test-docker/buildAndTestDocker.ts
        env:
          CI: true
