name: Docker image test
on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main

jobs:
  test-docker-image:
    name: Test Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install node packages
        run: |
          pnpm install --frozen-lockfile
        env:
          CI: true
      - name: Test docker image
        working-directory: scripts/
        run: pnpx ts-node -- ./build-test-docker/buildAndTestDocker.ts
        env:
          CI: true
