name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node packages
      run: |
        yarn install
      env:
        CI: true
    - name: Check code quality on server
      working-directory: server/
      run: |
        yarn prettier:check
        yarn eslint:check
        yarn ts:check
        yarn test
