name: Unit Tests
on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  test-server:
    name: Serverside unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install node packages
        run: |
          pnpm install
        env:
          CI: true
      - name: Run tests on server
        working-directory: server/
        run: |
          pnpm test
        env:
          CI: true
