name: Unit Tests
on:
  push:
    branches:
      - main
      - stable
  pull_request:

jobs:
  test-server:
    name: Serverside unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install node packages
        run: |
          yarn install
        env:
          CI: true
      - name: Run tests on server
        working-directory: server/
        run: |
          yarn test
        env:
          CI: true
